# Generated by Django 5.2.2 on 2025-06-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Admissions', 'Admissions'), ('Accounts', 'Accounts')], max_length=20),
        ),
    ]
