# Generated by Django 5.2.2 on 2025-06-17 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lead_code', models.CharField(max_length=20)),
                ('lead_name', models.CharField(default=None, max_length=20)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default=None, max_length=20)),
                ('university', models.CharField(default=None, max_length=50)),
                ('education_consultant', models.CharField(default=None, max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('student_ref_no', models.IntegerField(default=0)),
                ('intake', models.CharField(default=None, max_length=20)),
                ('scholarship', models.IntegerField(default=0)),
                ('cashback_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('referal_cashback', models.IntegerField(default=0)),
                ('semesters', models.IntegerField(default=0)),
                ('tuition_fee', models.IntegerField(default=0)),
                ('coe_issue_date', models.DateField(blank=True, null=True)),
                ('course_start_date', models.DateField(blank=True, null=True)),
                ('course_end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommissionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claiming_branch', models.CharField(max_length=100)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_earned', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admissions.student')),
            ],
        ),
    ]
