# Generated by Django 5.2.2 on 2025-06-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lead_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
