# Generated by Django 5.2.2 on 2025-06-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_alter_student_lead_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lead_name',
            field=models.CharField(max_length=100),
        ),
    ]
